services:
    motion_detect_cam-dev:
        container_name: motion_detect_cam-dev
        image: ${IMAGE_NAME}
        volumes:
            - ./Volumes:/App/Volumes
        network_mode: "host"
    # motion_detect_cam01:
    #     container_name: motion_detect_cam01
    #     extends: motion_detect_cam-dev
    # motion_detect_cam02:
    #     container_name: motion_detect_cam02
    #     extends: motion_detect_cam-dev
    # motion_detect_cam03:
    #     container_name: motion_detect_cam03
    #     extends: motion_detect_cam-dev