# Use root/example as user/password credentials
version: "3.7"

services:
    motion_detect:
        image: ${IMAGE_NAME}
        container_name: ${CONTAINER_NAME}
        volumes:
            - ./Volumes:/App/Volumes